import type { Metadata } from "next";
import localFont from "next/font/local";
import { Cormorant } from "next/font/google";
import "./globals.css";

// Import Components //
import LenisScroll from "@/components/organisms/lenis-scroll";
import { NavbarProvider } from "@/components/organisms/navbar-context";
import Navbar from "@/components/molecules/navbar";

const cormorant = Cormorant({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
});

const kodemono = localFont({
	src: "./fonts/kodemono-regular.ttf",
	weight: "400",
	style: "normal",
	variable: "--kode-mono",
});

const aeonikLight = localFont({
	src: "./fonts/aeonik-light.otf",
	weight: "300",
	style: "normal",
	variable: "--aeonik-light",
});

const aeonikRegular = localFont({
	src: "./fonts/aeonik-regular.otf",
	weight: "400",
	style: "normal",
	variable: "--aeonik-regular",
});

const aeonikMedium = localFont({
	src: "./fonts/aeonik-medium.otf",
	weight: "500",
	style: "normal",
	variable: "--aeonik-medium",
});

export const metadata: Metadata = {
	title: "ALCHEMIST",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${cormorant.className} ${aeonikLight.variable} ${aeonikRegular.variable} ${aeonikMedium.variable} ${kodemono.variable}`}
		>
			<body className="bg-[#151515]">
				<NavbarProvider>
					<Navbar />
					<LenisScroll>{children}</LenisScroll>
				</NavbarProvider>
			</body>
		</html>
	);
}
