import type { Metadata } from "next";
import localFont from "next/font/local";
import { Cormorant, Kode_Mono } from "next/font/google";
import "./globals.css";

// Import Components //
import Navbar from "@/components/organisms/navbar";

const cormorant = Cormorant({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
});

const kodemono = Kode_Mono({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--kode-mono",
});

const aeonikLight = localFont({
	src: "./fonts/aeonik-light.otf",
	weight: "300",
	style: "normal",
	variable: "--aeonik-regular",
});

const aeonikRegular = localFont({
	src: "./fonts/aeonik-regular.otf",
	weight: "400",
	style: "normal",
	variable: "--aeonik-regular",
});

const aeonikMedium = localFont({
	src: "./fonts/aeonik-medium.otf",
	weight: "500",
	style: "normal",
	variable: "--aeonik-medium",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`scroll-smooth ${cormorant.className} ${aeonikLight.variable} ${aeonikRegular.variable} ${aeonikMedium.variable} ${kodemono.variable}`}
		>
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
