import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Import Components //
import LenisScroll from "@/components/organisms/lenis-scroll";
import NavbarNew from "@/components/molecules/navbar";

const aeonikLight = localFont({
	src: "./fonts/aeonik-light.otf",
	weight: "300",
	style: "normal",
	variable: "--aeonik-light",
});

const aeonikRegular = localFont({
	src: "./fonts/aeonik-regular.otf",
	weight: "400",
	style: "normal",
	variable: "--aeonik-regular",
});

const aeonikMedium = localFont({
	src: "./fonts/aeonik-medium.otf",
	weight: "500",
	style: "normal",
	variable: "--aeonik-medium",
});

export const metadata: Metadata = {
	title: "ALCHEMIST",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${aeonikLight.variable} ${aeonikRegular.variable} ${aeonikMedium.variable}`}
		>
			<body className="bg-bgbase">
				<NavbarNew />
				<LenisScroll>{children}</LenisScroll>
			</body>
		</html>
	);
}
